// AUTO-GENERATED by scripts/generate-blur.ts — do not edit by hand.
// Regenerate with: bun run gen:blur

import { marketingAssetUrl } from "@/lib/marketing-assets";

export const blurPlaceholders: Record<string, string> = {
  [marketingAssetUrl("projects/ballaratboxsports1.png")]:
    "data:image/webp;base64,UklGRsoAAABXRUJQVlA4WAoAAAAQAAAADwAACgAAQUxQSFwAAAABf6CgbRuGP+Se/YGIiKyXVVVGhcGqtm0b63ocv/tI4Ga4f36JoIUAVwMiiHMiiCCEDDJE9D/mtZSybK8BoLAEMP0JIIcpgTyMBFIYgqQY3D2P+TEAFHut53HdH1ZQOCBIAAAAMAIAnQEqEAALAAOAWiWYAnQA9j7UyxIH6QAA/vF7m077J8WK4WwUqH0w3uJmZOjfFHjrMue2u8pD4Yi1idIktwmeRTPU6YAA",
  [marketingAssetUrl("projects/ballaratboxsports2.png")]:
    "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAA4BaJZwAAxZnDuhKAAD+9Qaj1NAK7joKBSI4DhpC+u/oaEWtSavg8sUN5G3GtbfcdDlofmeNrA89JouBssn6FqAA",
  [marketingAssetUrl("projects/ballaratboxsports3.png")]:
    "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoQAAsAA4BaJbACdADyvAAA/FHYL5FUI45FFHpsPaMaS6XIb/4D+Jf5WrfAAA==",
  [marketingAssetUrl("projects/dtc1.png")]:
    "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAgCdASoHABAAA4BaJZACdGuAt/8Dz3MggAD+7/z61h6DYfyQk9tz0DwhLsLmWD6usQPaSTItJnKgvmccdnXsqZwsAAAA",
  [marketingAssetUrl("projects/dtc2.png")]:
    "data:image/webp;base64,UklGRqYAAABXRUJQVlA4WAoAAAAQAAAADAAADwAAQUxQSBoAAAABF3D0/4iIwSDbSLt3nORUXyCi/8mLOoDqAFZQOCBmAAAA8AEAnQEqDQAQAAOAWiWwAnQAuDUh0JiQAP7iGlFojiHNAm4Vfw7kC6L2sjK6+Ns3KmdK2x8O7TNjQXnHIDByt6Gbn2AECWDXSvaJo+LM3ry31BKLYKUBjvoYK/yZyoubUYmCYAAA",
  [marketingAssetUrl("projects/dtc3.png")]:
    "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoHABAAA4BaJYwC7AD6A+y8AAD+8j08FoKbNMvvyRd+YNv2WbIq0ylbmWGe7ovj/1mUs861b75l2Bl7JK1BN3Sd46TpXDnRvwAAAA==",
  [marketingAssetUrl("projects/gotnextDashboard.png")]:
    "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAABwAQCdASoQAAkAA4BaJaUwAAGIAAD+9F4uVkIDdbP4uwgAAAA=",
  [marketingAssetUrl("projects/gotnextHero.png")]:
    "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkAA4BaJYwAAp0uFFrAAP75GHKMWTqI/rFK8FeMMB7mXCHmk5lLda3qAAAA",
  [marketingAssetUrl("projects/leadly1.png")]:
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4WAoAAAAQAAAADwAACgAAQUxQSBMAAAABD3D//4iIIBZM8pfeG0JE/7MFAFZQOCAkAAAAMAEAnQEqEAALAAOAWiWkAANwAP7x4mGdttdfLQcRFsxs0AAA",
  [marketingAssetUrl("projects/leadly2.png")]:
    "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoQAAsAA4BaJZQC7AEOSr8gAP72QDQ/7eUYMCc0sZnqxyDPKPjJ+jzkPHoAAA==",
  [marketingAssetUrl("projects/thomasbewick1.png")]:
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAsAA4BaJQBOgBh6TmsFgAD9AEeY+YpjDvLH+AL+CfdnR+wZ5jQF80gIFlNSlqt5GO4pDpNdwDXNzBDGAChmBKndmwV1mjG9asvfFkajfGouQAAAAA==",
  [marketingAssetUrl("projects/thomasbewick2.png")]:
    "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoQAAsAA4BaJZQC7AEO5HqyxN8AAP4nvyCw8HWmFguVm0dBkpT4+JSxAlpPVqHncgM8rhtuSx8AAA==",
  [marketingAssetUrl("projects/tradeMoai1.png")]:
    "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAsAA4BaJZwAAueB6VdxMAD+939vhSQBf4+4MC5lgjUgbpcRBQAA",
  [marketingAssetUrl("projects/tradeMoai2.png")]:
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJQBdgCHgBiUfaj4AAP724G/I6BIgGIrVZ4snGhJUQuzUtO3+zl+FfUE+Oa6CEDqxGizkKrMfxeptSEMAE/TJQj8POy8AAAA=",
  [marketingAssetUrl("projects/wabisabi1.png")]:
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAA4BaJQBdgCIGxlYNBoAA4n7U11oP122iMr4nkoVKxThBziPqQ4k4Pi7sLodS6WybyUt7QgwLDEHaOKBD9QDO9SLjtcnDTPbv1ggAAA==",
  [marketingAssetUrl("projects/wabisabi2.png")]:
    "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsAA4BaJZwAAp/WzGVrSAAA/vK0vhNb4YXb0LtpoU3keVXSLleZkBxEMcZDCk829l7ar49MQFl6X5exBN+pLC974AAA",
  [marketingAssetUrl("projects/wabisabi3.png")]:
    "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAsAA4BaJZQCw7Ef27+5AsoAAP7ytSFN8jM4d/J3rEg5jxjGN+6c/qPkUCSQ8+VU7/dN29z0QMp41TcaajsIKaPtX9i9LIdMskXug9BIEVYAAAA=",
  [marketingAssetUrl("whyus/code.png")]:
    "data:image/webp;base64,UklGRs4AAABXRUJQVlA4WAoAAAAQAAAADwAADAAAQUxQSGoAAAAFuQpE9D/AMADSNmB/b0/ooUm6C53eEDEBCtu2QdqO4ZDxoFjsTmAABqfdouiRCfwZyCZ2MnkjEATq0OxkYr9Ij3ZvbV97y8Mv+yUfWmqSvQNLzjMdKPwTAxDbhRASiMiCXn34mhUW0rYQVlA4ID4AAADwAQCdASoQAA0AA4BaJbACdLoAAqSqnkAA/o07Tuds3YO5bZPbJfZIY2rSL4KD/gdkUUP8EKX7FNjszAAAAA==",
  [marketingAssetUrl("whyus/communication.png")]:
    "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAA0AA4BaJbACdADvezjTogAA/vUccr/dQXvqjRnXQrwaXzGtQ5Hzm8+gQHRVFAdDjx0AAAA=",
  [marketingAssetUrl("whyus/flexible.png")]:
    "data:image/webp;base64,UklGRqQAAABXRUJQVlA4WAoAAAAQAAAADwAADAAAQUxQSEUAAAABYBvbVqL+q2AoRjd0LwFCt2jRBiJiAiBZz8yVQMalNr9acnaZlG2u1+bZ93N57hvvtXn2PXXM1ucklMlUYgJo3jNnBAAAVlA4IDgAAADwAQCdASoQAA0AA4BaJbACdAD0cwI4UcAA/vAzdaM4azgb1KR7Xlvdzjf//BWb0smkIFD5AoAAAA==",
  [marketingAssetUrl("whyus/quality.png")]:
    "data:image/webp;base64,UklGRrQAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEkAAAABP6CobSOGP8RS6Pv2pBER8fvJE0BRbFsJFb4UwCqw1wIMDbQB/RdWIaL/atu2YeytJnesnFJKdTsEAJDNioOFT/g/bvmuXX9vAFZQOCBEAAAAcAEAnQEqEAAJAAOAWiWwAnQBiEAA/vC9X5PFjsgvR+6PzeMqOONvv9flDhpT7/2kyOj2O+YatlUeafv3Fo1igqgAAAA=",
  [marketingAssetUrl("whyus/speed.png")]:
    "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABwAQCdASoQAA0AA4BaJbACdAF1AAD+8BQXx9d2CyhVY3kILaVhphBI6ewu+J93lLd3QAAA",
};
