/**
 * Generates tiny blurred LQIP (low-quality image placeholder) data URLs for the
 * gallery images rendered through <RevealImage>. These are baked, static blurs —
 * they let us cross-fade "out of focus → sharp" using only opacity (compositor
 * cheap) instead of animating `filter: blur()` on full-size images every frame.
 *
 * Run after adding/replacing images in the covered folders:
 *   bun run scripts/generate-blur.ts
 *
 * Output: lib/blur-placeholders.ts (a `public path -> data URL` map).
 */

import fs from "fs";
import path from "path";
import sharp from "sharp";

/** Folders whose images are rendered via <RevealImage> and benefit from LQIP. */
const COVERED_DIRS = ["projects", "whyus"];
const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".webp"]);
const PUBLIC_DIR = path.join(process.cwd(), "public");
const OUTPUT_FILE = path.join(process.cwd(), "lib", "blur-placeholders.ts");

async function blurDataUrlFor(absPath: string): Promise<string> {
  const buffer = await sharp(absPath)
    .resize(16, 16, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();
  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function main() {
  const entries: Record<string, string> = {};

  for (const dir of COVERED_DIRS) {
    const absDir = path.join(PUBLIC_DIR, dir);
    if (!fs.existsSync(absDir)) continue;

    for (const file of fs.readdirSync(absDir).sort()) {
      if (!IMAGE_EXTS.has(path.extname(file).toLowerCase())) continue;
      const absPath = path.join(absDir, file);
      const publicPath = `/${dir}/${file}`;
      entries[publicPath] = await blurDataUrlFor(absPath);
    }
  }

  const keys = Object.keys(entries);
  const body =
    `// AUTO-GENERATED by scripts/generate-blur.ts — do not edit by hand.\n` +
    `// Regenerate with: bun run scripts/generate-blur.ts\n\n` +
    `export const blurPlaceholders: Record<string, string> = {\n` +
    keys
      .map(
        (key) => `  ${JSON.stringify(key)}: ${JSON.stringify(entries[key])},`,
      )
      .join("\n") +
    `\n};\n`;

  fs.writeFileSync(OUTPUT_FILE, body);
  console.log(`Wrote ${keys.length} blur placeholders to ${OUTPUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
