/**
 * Generates tiny blurred LQIP (low-quality image placeholder) data URLs for the
 * gallery images rendered through <RevealImage>. These are baked, static blurs —
 * they let us cross-fade "out of focus → sharp" using only opacity (compositor
 * cheap) instead of animating `filter: blur()` on full-size images every frame.
 *
 * Run after uploading/replacing one of the covered R2 images:
 *   bun run gen:blur
 *
 * Output: lib/blur-placeholders.ts (a `public URL -> data URL` map).
 */

import fs from "fs";
import path from "path";
import sharp from "sharp";
import { BLUR_ASSET_PATHS, marketingAssetUrl } from "../lib/marketing-assets";

const OUTPUT_FILE = path.join(process.cwd(), "lib", "blur-placeholders.ts");

async function blurDataUrlFor(imageUrl: string): Promise<string> {
  const response = await fetch(imageUrl);
  if (!response.ok) {
    throw new Error(`Could not fetch ${imageUrl}: ${response.status}`);
  }

  const source = Buffer.from(await response.arrayBuffer());
  const buffer = await sharp(source)
    .resize(16, 16, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();
  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function main() {
  const entries: Record<string, string> = {};

  for (const assetPath of BLUR_ASSET_PATHS) {
    entries[assetPath] = await blurDataUrlFor(marketingAssetUrl(assetPath));
  }

  const keys = Object.keys(entries);
  const body =
    `// AUTO-GENERATED by scripts/generate-blur.ts — do not edit by hand.\n` +
    `// Regenerate with: bun run gen:blur\n\n` +
    `import { marketingAssetUrl } from "@/lib/marketing-assets";\n\n` +
    `export const blurPlaceholders: Record<string, string> = {\n` +
    keys
      .map(
        (key) =>
          `  [marketingAssetUrl(${JSON.stringify(key)})]: ${JSON.stringify(entries[key])},`,
      )
      .join("\n") +
    `\n};\n`;

  fs.writeFileSync(OUTPUT_FILE, body);
  console.log(`Wrote ${keys.length} blur placeholders to ${OUTPUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
